version: "3.9"

services:
  backend:
    image: thealdi/stoergeler-backend:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    container_name: stoergeler-backend
    networks:
      stoergeler_net:
        ipv4_address: 172.18.0.4
    ports:
      - "8001:8000"
    environment:
      FRITZBOX_ADDRESS: ${FRITZBOX_ADDRESS:-fritz.box}
      FRITZBOX_USERNAME: ${FRITZBOX_USERNAME:-}
      FRITZBOX_PASSWORD: ${FRITZBOX_PASSWORD:-}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS:-60}
      DEVICE_LOG_POLL_INTERVAL_SECONDS: ${DEVICE_LOG_POLL_INTERVAL_SECONDS:-60}
      DATABASE_PATH: /app/data/stoergeler.db
      SMTP_SERVER: ${SMTP_SERVER:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-}
      SMTP_TLS: ${SMTP_TLS:-True}
      SMTP_SSL: ${SMTP_SSL:-False}
      REPORT_RECIPIENTS: ${REPORT_RECIPIENTS:-}
      REPORT_EMAIL_BODY: ${REPORT_EMAIL_BODY:-}
      REPORT_SCHEDULE_CHECK_INTERVAL_SECONDS: ${REPORT_SCHEDULE_CHECK_INTERVAL_SECONDS:-3600}
    volumes:
      - /volume1/docker/stoergeler/data:/app/data

  frontend:
    image: thealdi/stoergeler-frontend:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    container_name: stoergeler-frontend
    networks:
      stoergeler_net:
        ipv4_address: 172.18.0.5
    depends_on:
      - backend
    ports:
      - "8080:80"

networks:
  stoergeler_net:
    external: true
    name: stoergeler
